import { Inter, Poppins } from "next/font/google";
import NavigationBar from "@/Components/Navigationbar";
import FooterSection from "@/Components/FooterSection";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: "Brandon Roulstone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <NavigationBar />

        {children}

        <FooterSection />
        
      </body>
    </html>
  );
}
